apiVersion: v1
kind: PersistentVolume
metadata:
  name: uni-docs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /run/desktop/mnt/host/c/Users/veljk/Desktop/Uni
    type: Directory
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uni-docs-pvc
  namespace: uni-assistent
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  volumeName: uni-docs-pv
