apiVersion: v1
kind: Service
metadata:
  name: uni-app
  namespace: uni-assistent
spec:
  selector:
    app: uni-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
